### ISSUE TITLE
find_element_by_xpath has been removed from selenium

### ISSUE THREAD

**Issue by leggewie** [Kalebu/alright#102]
find_elements_by_* methods have been [removed from selenium 4.3.0](https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES).  find_by_username now fails.

```
>>> messenger.find_by_username("NEO")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/alright/__init__.py", line 166, in find_by_username
    opened_chat = self.browser.find_elements_by_xpath(
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath'
```

You [should use the find_element method](https://stackoverflow.com/questions/72754651/attributeerror-webdriver-object-has-no-attribute-find-element-by-xpath) instead now.

**Comment by leggewie** [comment]
I thought I was running the latest code via a pip install.  But it seems like that is not the case.  Code inspections suggests this problem was fixed in commit bff87c9b85c66e0917.  Time to make another release to pypi.org?  I checked the output of "git tag" and found it hard or rather impossible to understand what code corresponds to what release.

**Comment by Kalebu** [comment]
Hi @leggewie

Sure, The latest release was July last year, I guess it is time to make another one and push it to PyPI[ON IT ]

**Comment by Kalebu** [comment]
I have already published a new release to pypi with new changes update 

I will mark this issue as resolved

**Comment by leggewie** [comment]
Thanks, much appreciated!
