### ISSUE TITLE
improvements to storage of user-specific data

### ISSUE THREAD

**Issue by leggewie** [Kalebu/alright#104]
alright [currently](https://github.com/Kalebu/alright/blob/1e70f90470177f7492df7a807753d1939320d031/alright/__init__.py#L58-L63) is inconsistent across platforms in where it stores its user-specific data.  On Windows, things are stored under C:/Temp/ChromeProfile, for other platforms a folder User_Data in the current directory is used.  This can lead to clutter and data-loss.  I have a suspicion this is at least partially the reason why I see alright sometimes work and then a minute later (in a different directory?) fail (#103).

There is some convention and policy where this data ought to be stored.  There is also a [python library](https://github.com/platformdirs/platformdirs) to do the heavy-lifting in the background. I will try and publish some code for review in the following days.

**Comment by Kalebu** [comment]
Hello @leggewie 

Not much thought was given in terms of where to store user's data and problems became more serious when you consider the multiplatform, I think this update will be incredibly useful, Are you still working on  it ?

**Comment by leggewie** [comment]
I kind of paused but I'm certainly still having it on my todo list

**Comment by leggewie** [comment]
I have pushed a proposal.

Do we actually this need the platform-specific coding or can we move everything (start-maximized, profile-directory) outside of the if-statement?
