### ISSUE TITLE
send_message1 has an error: AttributeError: 'WebElement' object has no attribute 'aria_role'

### ISSUE THREAD

**Issue by neeraj-satyaki** [Kalebu/alright#108]
To fix this @line number 425 and 439 i changed form i.aria_role to i.get_attribute('role')

**Comment by neeraj-satyaki** [comment]
Please do update this on the repo

**Comment by Kalebu** [comment]
Pushed, Thank you @neeraj-satyaki

**Comment by leggewie** [comment]
please reopen as commit 5c4833eccf regressed on this issue
