### ISSUE TITLE
send_picture closes too quickly, making it unable to send the image

### ISSUE THREAD

**Issue by PhilipWee** [Kalebu/alright#11]
Right now send_picture closes too quickly, resulting in the image not being sent

I have temporarily resolved it myself using the following time.sleep:

```filename = os.path.realpath(picture)
            self.find_attachment()
            # To send an Image
            imgButton = self.wait.until(EC.presence_of_element_located(
                (By.XPATH, '//*[@id="main"]/footer//*[@data-icon="attach-image"]/../input')))
            imgButton.send_keys(filename)
            self.send_attachment()
            time.sleep(5)
            print(f"Picture has been successfully sent to {self.mobile}")```

I'm not too sure how selenium works but it would be great if we could wait for the image to send before moving to the next person

**Comment by Kalebu** [comment]
Hi @PhilipWee 

At the time of development, the timing worked perfectly,

Thanks for noticing that, I'm sure it's going to help other folks facing the same issue 

Best regards
Kalebu

**Comment by euriconicacio** [comment]
I think this was solved with today's delivery on `send_attachment` update. Could you please confirm, and open a new issue if it persists, @PhilipWee? Thanks a lot!
