### ISSUE TITLE
Chrome closes before sending message

### ISSUE THREAD

**Issue by Supposable** [Kalebu/alright#113]
When trying to send a message it opens whatsapp web on chrome, types out the message and closes before actually sending the message. Anyone know why this is happening?

`from alright import WhatsApp

messenger = WhatsApp()
messenger.find_user('1234')
message = 'test'

messenger.send_message(message)`

**Comment by math-milan** [comment]
hello just one mor line containing
`messenger.close_when_message_successfully_sent()`
with this line the browser close only after the mesage has ben sent out
