### ISSUE TITLE
messenger.send_picture is not working, Image is Loaded but its NOT sending

### ISSUE THREAD

**Issue by naseemap47** [Kalebu/alright#117]
I think WhatsApp might have changed the Xpath for the send button
@Kalebu Please give a look on this

**Comment by Yohanes-arch** [comment]
yes I encountered the same problem too, and its not only for images I think, its for all the attachments

**Comment by abdulmelikbekmez** [comment]
I made a small update for this issue, you can check it out.
It works fine for me.

#118

**Comment by naseemap47** [comment]
> I made a small update for this issue, you can check it out. It works fine for me.
> 
> #118

Its working :rocket: 
So I am closing this issue.
