### ISSUE TITLE
Sending message without opening browser

### ISSUE THREAD

**Issue by jaydip-c** [Kalebu/alright#12]
Is it possible to send the messages while whatsapp-web tab is closed? Of course I would open it to read the qr code. But once that is done, I would close the tab. Is it possible to send the message even then?

**Comment by Kalebu** [comment]
Hi @jaydip-c 

I think that's doable perhaps I never tried it myself, If you run selenium in headless mode, it will open the chrome in the background, so you need to add extra arguments under the chrome_options property in alright with these new arguments

```python
options.add_argument('--headless')
options.add_argument('--disable-gpu')  
```

Here a [StackOverflow](https://stackoverflow.com/questions/46920243/how-to-configure-chromedriver-to-initiate-chrome-browser-in-headless-mode-throug) reference for you

**Comment by euriconicacio** [comment]
Hi, @jaydip-c. Indeed, the alternatives presented by Kalebu solve the visibility issue. Hope they are helpful - please, feel free to reach out in case of any further doubt.

**Comment by rohitsingh30** [comment]
I think this is not working. Currently, it is throwing this error while trying sending an image

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div aria-disabled="false" role="button" tabindex="0" class="_26lC3" data-tab="10" title="Attach" aria-label="Attach">...</div> is not clickable at point (435, 569). Other element would receive the click: <div class="p357zi0d ktfrpxia nu7pwgvd ac2vgrno sap93d0t r15c9g6i _1vAZI">...</div>
  (Session info: headless chrome=100.0.4896.127)
