### ISSUE TITLE
Other Browsers

### ISSUE THREAD

**Issue by jaydip-c** [Kalebu/alright#13]
I am using Brave browser. Is it possible to open whatsapp web page in a Brave tab? Or, do I have to install Chromium?

Thanks.

**Comment by Kalebu** [comment]
Hi @jaydip-c 

So I'm using Brave browser but I had an issue with selenium failing to open a brave browser using chrome driver,
whereby with the current implementation chromedriver is mandatory.

Therefore I suggest you install Chrome (Tested ) or Chromium (Not so sure but might work) for alright to work

**Comment by vadolasi** [comment]
Try this:

```
from selenium import webdriver
from alright import WhatsApp

options = webdriver.ChromeOptions()
options.add_argument("user-data-dir=./user_data")
options.binary_location = "<brave path>"

driver = webdriver.Chrome("<chromedriver path>", options=options)
messenger = WhatsApp(driver)
```

**Comment by euriconicacio** [comment]
This was addressed and merged.
