### ISSUE TITLE
Project doesn't seem to work 

### ISSUE THREAD

**Issue by alexferra** [Kalebu/alright#132]
2023-08-23 15:57:05,094 - root -- [INFO] >> Message sent successfuly to Person

I get this but it doesn't send message. other functions like via phone number or get messages don't run either.

**Comment by Mohammad-Rafiee** [comment]
Me too. The reason is, the HTML elements aren't correct. We should edit the elements in the code so they could work.

**Comment by Kalebu** [comment]
Xpath issues has been resolved, please update the package 

```bash

pip install --upgrade alright

```
