### ISSUE TITLE
Sending picture message failing

### ISSUE THREAD

**Issue by manthrayilsubin** [Kalebu/alright#14]
It seems there is change in dom.The send picture message is not working.

**Comment by manthrayilsubin** [comment]
send button xpath to be modified as 
//*[@id="app"]/div[1]/div[1]/div[2]/div[2]/span/div[1]/span/div[1]/div/div[2]/div/div[2]/div[2]/div/div/span

**Comment by Kalebu** [comment]
Hi @manthrayilsubin 

Thanks for pointing that, can you create a pull request for that and I will approve it right away

Best regards
Kalebu

**Comment by Ramacap** [comment]
> send button xpath to be modified as
> //*[@id="app"]/div[1]/div[1]/div[2]/div[2]/span/div[1]/span/div[1]/div/div[2]/div/div[2]/div[2]/div/div/span

thanks! it worked

**Comment by VanshKela** [comment]
Is It correct?

**Comment by euriconicacio** [comment]
This is fixed. Can we please close this issue, @Kalebu, and maintainers?
