### ISSUE TITLE
Close the browser after running the code

### ISSUE THREAD

**Issue by pNew700** [Kalebu/alright#15]
what command should I use to close the browser after running the code? I've tried driver.close() and driver.quit() , but none of it worked

**Comment by vinifroes** [comment]
This work for me...

> alright/__init__.py

`
    def close(self):
        self.browser.close()
`

> example.py

`
import time
...
time.sleep(5)
messenger.close()
`

**Comment by euriconicacio** [comment]
Hi, @pNew700 and @vinifroes. This functionality was implemented on the `close_when_message_successfully_sent` method. Thanks for the contribution!

**Comment by allesman** [comment]
Thanks for the implementation! However, sometimes the time the program waits for the message to be sent is unreasonably long, so I would like to have method that instantly closes the window.
