### ISSUE TITLE
Failed to create data directory

### ISSUE THREAD

**Issue by chetan6780** [Kalebu/alright#2]
Hello, I am having this issue, not sure others having the same issue or not but I just want to let you know this
![image](https://user-images.githubusercontent.com/62825092/123045716-dd2dc500-d418-11eb-9243-f54156c1ee92.png)
![image](https://user-images.githubusercontent.com/62825092/123045921-1d8d4300-d419-11eb-9b53-e82881de219f.png)

After surfing on the web and trying different solution it still giving the same issue, so I have commented line 26 in __init__.py, Now its opening what's app but not sending messages.

**Comment by Kalebu** [comment]
You have to make sure that only one instance of your chrome browser is running otherwise it will raise an error, so close an existing chrome window and only one being controlled by alright (One at the time).

If not you can try to run your script as administrator, Let me know how it goes

**Comment by chetan6780** [comment]
@Kalebu I have run the script as an administrator and no other instance of crome was running but still, it's not working.
I am on windows and followed the documentation.
if possible, can you make a small screencast for a demonstration?

**Comment by Kalebu** [comment]
Just made a short screencast about that, Here a a link https://youtu.be/yitQTt-NukM

**Comment by Kalebu** [comment]
So maybe cloning the repository and then just import alright as a package without installing it

So as the User_Data can be created locally and not on system files

**Comment by Kalebu** [comment]
Let me know how it goes

**Comment by chetan6780** [comment]
> So maybe cloning the repository and then just import alright as a package without installing it
> 
> So as the User_Data can be created locally and not on system files

I did same, like copied __init__.py and then added code at last

**Comment by chetan6780** [comment]
> Just made a short screencast about that, Here a a link https://youtu.be/yitQTt-NukM

nice demo, I will try it on ubuntu and let you know.

**Comment by Kalebu** [comment]
Cool, Thanks for suggestions, comments, and contributions 

It makes a smooth path other devs  who might have samiliar issues 

cheers

**Comment by chetan6780** [comment]
hello @Kalebu that solution you told in #7 is worked for me on windows.

**Comment by Kalebu** [comment]
Cool Thanks for the feedback just made it default and already pushed it on PyPI so that future users don't face this challenge. 

In the Next version, Let's expect the capability to read messages, still researching on possibilities 

I can now both of the issues
