### ISSUE TITLE
Check if number is invalid

### ISSUE THREAD

**Issue by VanshKela** [Kalebu/alright#26]
Currently if the number is invalid or not on Whatsapp. Application does nothing.

**Comment by Kalebu** [comment]
Any idea to resolve this ?

**Comment by VanshKela** [comment]
Will it be possible?

**Comment by VanshKela** [comment]
We can also do one more thing we can create another wait WebDriverWait that waits for 20 seconds rather than 600 and can wait for XPath for input box if not found we can just return?
