### ISSUE TITLE
send message text error

### ISSUE THREAD

**Issue by matiastiberio** [Kalebu/alright#28]
Hi I'm currently trying to send a message and a image, but it doesn't sends the message and stands still in that part:

from alright import WhatsApp
messenger = WhatsApp()
numbers = ['14155238886']
for number in numbers:
        messenger.find_user(number)
        messenger.send_message("I wish you a Merry X-mass and Happy new year ")
        messenger.send_picture('/Users/matiasgonzalotiberio/Desktop/Whatsapp-Python/1451023683665.jpeg')

<img width="1438" alt="Captura de Pantalla 2021-09-14 a la(s) 12 50 04" src="https://user-images.githubusercontent.com/90711454/133291116-af8ed9d9-ef79-4750-adbf-21f0ffea5ef6.png">
<img width="1153" alt="Captura de Pantalla 2021-09-14 a la(s) 12 50 13" src="https://user-images.githubusercontent.com/90711454/133291144-a26906e7-fdfe-4cc1-ad47-b1a06a59e10a.png">

As you can see it starts and throws no error, but the message text isn't sent

**Comment by duclenk** [comment]
im facing the same issue, it happen last day.
before that everything worked well

**Comment by Kalebu** [comment]
I think WhatsApp might have changed the Xpath for the send button, will give a look

**Comment by duclenk** [comment]
> I think WhatsApp might have changed the Xpath for the send button, will give a look

thanks, i hope i can use this library again. because help me alot for broadcasting message :(

**Comment by Ramacap** [comment]
> I think WhatsApp might have changed the Xpath for the send button, will give a look

facing same problem, do you know if they changed it ? thanks!!

**Comment by Ramacap** [comment]
> I think WhatsApp might have changed the Xpath for the send button, will give a look

Hi again i changed the xpath of the input_box and it worked again

'//*[@id="main"]/footer/div[1]/div/div/div[2]/div[1]/div/div[2]'

**Comment by Kalebu** [comment]
Thank you @Ramacap, Already included in the main branch

I highly appreciate
