### ISSUE TITLE
 send message with emojis

### ISSUE THREAD

**Issue by andersonfelipev** [Kalebu/alright#37]
Hey guys, does anyone know how to send messages that contain emojis?

**Comment by euriconicacio** [comment]
Hi, @andersonfelipev. A simple but powerful workaround is to use emojis in Unicode format, like this (an example of an emoji being printed through its Unicode in ipython):

<img width="196" alt="image" src="https://user-images.githubusercontent.com/5957301/172222164-ae4018b1-7509-40c0-a872-f6fc97098dd3.png">

A full list of emojis' Unicode values is presented here: https://unicode.org/emoji/charts/full-emoji-list.html.

Hope this is helpful!
