### ISSUE TITLE
How to send image with caption

### ISSUE THREAD

**Issue by victorterancas** [Kalebu/alright#38]
Is my first time making a coment in github, i am sending an "improvement" of "send_picture()". It is how to send a picture with text on it:

`
def send_picture(self, picture, message):
        try:
            filename = os.path.realpath(picture)
            self.find_attachment()
            # To send an Image
            imgButton = self.wait.until(EC.presence_of_element_located(
                (By.XPATH, '//*[@id="main"]/footer//*[@data-icon="attach-image"]/../input')))
            imgButton.send_keys(filename)
            inp_xpath = '//*[@id="app"]/div[1]/div[1]/div[2]/div[2]/span/div[1]/span/div[1]/div/div[2]/div/div[1]/div[3]/div/div/div[2]/div/div[2]'
            input_box = self.wait.until(EC.presence_of_element_located((
                By.XPATH, inp_xpath)))
            input_box.send_keys(message + Keys.ENTER)
            self.send_attachment()
            print(f"Picture has been successfully sent to {self.mobile}")
        except (NoSuchElementException, Exception) as bug:
            print(bug)
            print(f'Failed to send a picture to {self.mobile}')`

**Comment by Kalebu** [comment]
Hello @victorterancas, This is really interesting 

Can you please adding to the main codebase and submit your pull request 

Let me know if you would need assistance and any further clarification on that 

You can also read [How to make your first contribution](https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940)

Looking forward seeing your contribution 

Best regards 
Kalebu

**Comment by badi95** [comment]
Has this gotten merged in? I'd really like to use this feature.

**Comment by badi95** [comment]
Manually added this to my system, and tested it. Seemed to work fine, so I created a PR for it.

**Comment by badi95** [comment]
Issue ready to close?

**Comment by victorterancas** [comment]
Yes. Thank you guys, i am still learning how to use github. 😅. Thank you @badi95 for giving me credits for the code, you made a nice job.
