### ISSUE TITLE
Doesn't work on raspberry pi

### ISSUE THREAD

**Issue by therealcyber71** [Kalebu/alright#39]
Hello there, I'm migrating from pywhatkit and I loved your package, but there seems to be a problem whil I was working on a raspberry pi, the chrome driver installation is not being recognised by alright, how do I deal with this issue, please let me know asap.

**Comment by Sachit71** [comment]
Ok so I used a little bit of my brain and went through the documentation again, alright uses google chrome, whereas a rpi uses chromium, how do I change the browser driver installation?

**Comment by Sachit71** [comment]
I removed the web driver manager and simply installed the required driver, but now the it leads me to a deep link which whatsapp doesnt recognize

**Comment by Kalebu** [comment]
Hello @Sachit71 , I personally haven't tested alright outside the chrome browser 

The best I would advice for you is installing the Chrome browser

**Comment by Sachit71** [comment]
hello, @Kalebu thanks for responding, but the raspberry pi doesn't support chrome and hence uses a lighter chromium version, I will now close the issue.

**Comment by Sachit71** [comment]
oh yeah, I had another doubt, if I could know how you managed to stop WhatsApp web from asking for the QRcode again and again,  could work on it.

**Comment by Kalebu** [comment]
Hi @therealcyber71  I just noticed you didn't receive any response on this issue 

Apologize for the delay, things have been hectic but basically, we create a folder **UserData** to store the browser session including the QR code signing so next time it won't start from scratch?

ALso, Did you manage to make it work with Raspberry Pi ?

**Comment by Kalebu** [comment]
You can also refer to issue #31  (Making it work over Pi)

**Comment by therealcyber71** [comment]
> Hi @therealcyber71  I just noticed you didn't receive any response on this issue 
> 
> Apologize for the delay, things have been hectic but basically, we create a folder **UserData** to store the browser session including the QR code signing so next time it won't start from scratch?
> 
> ALso, Did you manage to make it work with Raspberry Pi ?

I managed to get the qr code to work just gotta hit save cookies, I haven't tested on the pi yet, I kinda moved on from that project haha but thanks for letting me know I'll get back to you asap
