### ISSUE TITLE
How to close the terminal after running the Alright wrapper?

### ISSUE THREAD

**Issue by LouisSchieferle** [Kalebu/alright#41]

**Comment by Kalebu** [comment]
Are you referring to closing the WhatsApp window or Terminal?

**Comment by euriconicacio** [comment]
@LouisSchieferle , if you intend to close the browser, the method for that has been implemented, check it out!

However, if you do want to close the terminal itself, try something like `exec python ./my_script.py` instead of simply `python ./my_script.py`.

Hope this is helpful.

**Comment by euriconicacio** [comment]
Additional tip, @LouisSchieferle: if you intend to close the browser, you can use `messenger.browser.quit()` on your code. Hope this is helpful!
