### ISSUE TITLE
Multiline Textmessage

### ISSUE THREAD

**Issue by LouisSchieferle** [Kalebu/alright#42]
Is it possible to send multiline textmessages with whatsapp without all of them being a separate text-message

**Comment by ronivaldo** [comment]
I am having the same issue here

**Comment by adesr** [comment]
hello, we found this workaround from someone's answer in StackOverflow thread and we can use it sucessfully. the idea is to split NewLines in message and simulate SHIFT+ENTER to browser.

`for msg in message.split("\n"):
    input_box.send_keys(msg)
    ActionChains(self.browser).key_down(Keys.SHIFT).key_down(Keys.ENTER).key_up(Keys.ENTER).key_up(Keys.SHIFT).perform()
input_box.send_keys(Keys.ENTER)`

**Comment by Kalebu** [comment]
Hi @adesr, This is cool, can you submit a pull request so we can this to the main distribution 

Thank you 
kalebu

**Comment by setijo** [comment]
from alright import WhatsApp
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
**from selenium.webdriver.common.keys import Keys**
import time
import datetime


chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--verbose')
chrome_options.add_argument('--disable-software-rasterizer')
driver = webdriver.Chrome(executable_path = '/usr/bin/chromedriver' ,chrome_options = chrome_options)

messenger = WhatsApp()
messenger.find_user('62xxxxxxxxx')
**messages = 'baris1\nbaris2\nbaris3'
messages = messages.replace("\n",(Keys.SHIFT+Keys.ENTER+Keys.SHIFT))**
messenger.send_message(messages)
time.sleep(5)
messenger.close()

**Comment by euriconicacio** [comment]
> Hi @adesr, This is cool, can you submit a pull request so we can this to the main distribution
> 
> Thank you kalebu

@Kalebu I'll add this to my current PR since it's really useful and the OP has not sent it, ok?

**Comment by euriconicacio** [comment]
Addressed through PR #58. 🙃
