### ISSUE TITLE
messenger.find_user not working with whatsapp web

### ISSUE THREAD

**Issue by ammarassoum** [Kalebu/alright#43]
Hi,
I tried to send a whatsapp message using the alright module but when I ran the code, Goggle Chrome was launched but asks me if I want to open the whatsapp app instead of sending the message via whatsapp web as expected.
Thanks for help.

# Here is my code
messenger = WhatsApp()
messenger.find_user('12345678')
messenger.send_message('Test of alright module')

![image](https://user-images.githubusercontent.com/48494981/153673963-fe18ef2e-34dc-498a-9db4-826c6ca7995b.png)

**Comment by idanless** [comment]
set "V" and open WhatsApp

**Comment by Kalebu** [comment]
Resolve on #50 #51
