### ISSUE TITLE
Get chat

### ISSUE THREAD

**Issue by sepehrmizani** [Kalebu/alright#48]
hi kalebu  
I think if this library can get the last chat of the user is It will be great

**Comment by sepehrmizani** [comment]
Hi @euriconicacio  I mean the last message sent to the user

**Comment by euriconicacio** [comment]
Awesome, we have a PR up for review that solves that issue. It's a tricky situation indeed, since the chats are not "ordered", but we managed to work that around.

**Comment by euriconicacio** [comment]
@sepehrmizani - sorry, I misunderstood your previous message, my mistake. Just added the [`get_last_message_received`](https://github.com/Kalebu/alright/blob/6cc5a3f09d523743670dab4c0159c3f0a1add661/alright/__init__.py#L579-L633) that solves your issue. Enjoy!

cc @Kalebu, FYI. Important update, along with others delivered during the day. I think we can release 1.5 now, maybe?
