### ISSUE TITLE
Noticed some grammar mistakes in README

### ISSUE THREAD

**Issue by chandansgowda** [Kalebu/alright#5]
If you're facing any issue or difficult with the usage of the package just raise one so as we can fix it as soon as possible. Difficult -- Difficulty and as -- that

**Comment by Kalebu** [comment]
Hey @chandansgowda  you can proceed to fixing it

**Comment by chetan6780** [comment]
hello @chandansgowda please fix this one also 
![image](https://user-images.githubusercontent.com/62825092/123070833-bcbe3480-d431-11eb-9016-aeb0f00e19ed.png)
 withour --> without

**Comment by Kalebu** [comment]
This already resolved by #6  I can now close the issue
