### ISSUE TITLE
WhatsApp Desktop

### ISSUE THREAD

**Issue by andybenichou** [Kalebu/alright#53]
Hi, when sending files or media, it opens WhatsApp Desktop and so stop. I saw that you fix this with send_message1, is it possible to fix this for all the others possibilities? 

Thanks

**Comment by Kalebu** [comment]
Hi @andybenichou 

Yes very possible, looking into this 

Thanks

**Comment by Kalebu** [comment]
Yes, I have updated ```find_user```, now it should work even if you a WhatsApp app installed 

And also 

I have added a new method ```send_direct_message``` that works well with both saved and unsaved contacts and you can do this by using the below snippet, It does assume your number is saved by default but you can change it by changing the ```saved``` parameter. 

```python
>>> messenger.send_direct_message(mobile, message, saved=True)
```

It does receive the following parameters;

1. **mobile[str]** - The mobile number of the user you want to send the message to
2. **message[str]** - The message you want to send
3. **saved[bool]** - If you want to send to a saved contact or not, default is False

Here is an example on how to use it;

```python
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
>>> >>> messenger.send_direct_message('25573652xxx', 'Hello')
2022-08-14 17:27:57,264 - root -- [INFO] >> Message sent successfuly to 
2022-08-14 17:27:57,264 - root -- [INFO] >> send_message() finished running!
>>> messenger.send_direct_message('25573652xxx', 'Who is This ?', False)
2022-08-14 17:28:30,953 - root -- [INFO] >> Message sent successfuly to 255736524388
2022-08-14 17:28:30,953 - root -- [INFO] >> send_message() finished running!
```
