### ISSUE TITLE
Whatsapp doesn't use whatsapp web

### ISSUE THREAD

**Issue by riccardoferti** [Kalebu/alright#55]
When trying to send msg on ubuntu, whatsapp shows to download Desktop (that doesn't exists) or to let you select to use whatsapp web.
I remember that last week it was working good, any advice? Thank you

**Comment by samratswami** [comment]
After new update from Whatsapp  only [Send Messages1] is working. Facing the same issue can anyone help?
Thanks

**Comment by Kalebu** [comment]
Hi guys 

I have added a new method ```send_direct_message``` that works well with both saved and unsaved contacts and you can do this by using the below snippet, It does assume your number is saved by default but you can change it by changing the ```saved``` parameter. 

```python
>>> messenger.send_direct_message(mobile, message, saved=True)
```

It does receive the following parameters;

1. **mobile[str]** - The mobile number of the user you want to send the message to
2. **message[str]** - The message you want to send
3. **saved[bool]** - If you want to send to a saved contact or not, default is False

Here is an example on how to use it;

```python
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
>>> >>> messenger.send_direct_message('25573652xxx', 'Hello')
2022-08-14 17:27:57,264 - root -- [INFO] >> Message sent successfuly to 
2022-08-14 17:27:57,264 - root -- [INFO] >> send_message() finished running!
>>> messenger.send_direct_message('25573652xxx', 'Who is This ?', False)
2022-08-14 17:28:30,953 - root -- [INFO] >> Message sent successfuly to 255736524388
2022-08-14 17:28:30,953 - root -- [INFO] >> send_message() finished running!
```
