### ISSUE TITLE
find_by_username search box XPATH does not work - updated it - and created close_browser method.

### ISSUE THREAD

**Issue by euriconicacio** [Kalebu/alright#56]
So, I'm using Pyhon 3.10.4, Chrome 102.0.5005.61 and Debian 9.13.

When trying to send a simple message, the code hang forever and nothing happened. While debugging, I noticed that the XPATH for the search_box on find_by_username was not correct.

Under my configuration, this is incorrect:

```
            search_box = self.wait.until(
                EC.presence_of_element_located(
                    (By.XPATH, '//*[@id="side"]/div[1]/div/label/div/div[2]')
                )
            )
```

And this is correct:

```
            search_box = self.wait.until(
                EC.presence_of_element_located(
                    (By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]')
                )
            )
```

I was wondering if this is happening to anyone else and if it depends on Chrome version or OS. If it does, I can work on a PR for it.

Thanks in advance for your attention.

@Kalebu @vadolasi

**Comment by euriconicacio** [comment]
In addition: I'm running a scheduled script to send a message to a group periodically. I added a close_browser method to the WhatsApp class too - it could be part of the PR as well.

**Comment by euriconicacio** [comment]
AND: we could check if a Chrome instance is already opened grabbing its `driver.session_id` - if it's not opened, it would return `None`; if it is opened, we could roll the code on a new tab (`body.send_keys(Keys.CONTROL + 't')`). 

I mean, I can address these improvements if you guys are ok with it - just need confirmation on the first one.

**Comment by Kalebu** [comment]
> 

Hi @euriconicacio 

I tried to use the method ```messenger.find_by_username``` and I'm experiencing the same issue 

Please submit your PR

Thank you

**Comment by euriconicacio** [comment]
@Kalebu, please find the PR [here](https://github.com/Kalebu/alright/pull/57). Thanks once again.
