### ISSUE TITLE
Alright with Edge

### ISSUE THREAD

**Issue by LucasLourencoo** [Kalebu/alright#77]
Can i use the alright with the edge?
i'm trying to use it, but everytime is shown to me a new error

There's the code:

from alright import WhatsApp
from selenium import webdriver
from selenium.webdriver.edge.service import Service as EdgeService
from webdriver_manager.microsoft import EdgeChromiumDriverManager

driver = webdriver.Edge(service=EdgeService(EdgeChromiumDriverManager().install()))
messenger = WhatsApp()

(I made it at the company that i work, but there i was using google. I felt the problem that u are being showed, about the xpath, and made what the people on de issues said, and worked. But now, i brought it to my house and i don't use google chrome, just edge)

**Comment by Kalebu** [comment]
Hi @LucasLourencoo 

Can you please share a snapshot of the error messages you're getting?

@euriconicacio

**Comment by LucasLourencoo** [comment]
![image](https://user-images.githubusercontent.com/102922249/184566257-d93610d7-041e-4d61-a14c-08651af38cae.png)


everytime that i run the same code that i wrote before, this error apears

**Comment by euriconicacio** [comment]
It is not finding EdgeChromium webdriver, as the error says. We can try to improve this and catch it as an exception, @Kalebu.

@LucasLourencoo, could you please to download/upgrade your EdgeChromium driver [here](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/?tabs=c-sharp) and retrying?

Thanks.

**Comment by euriconicacio** [comment]
Closing this since it has been unanswered for 2 months.
