### ISSUE TITLE
Check for new messages

### ISSUE THREAD

**Issue by nurgasemetey** [Kalebu/alright#8]
Does it support checking for new messages?

**Comment by Kalebu** [comment]
Hello @nurgasemetey, Currently **alright** does not support reading and checking for new messages

But expect it to be available in coming versions and you can also be one of the contributors for it 

Stay tuned

**Comment by euriconicacio** [comment]
Implemented! New method `check_if_given_chat_has_unread_messages` supports that request, given a query parameter with the chat name. Thanks for the contribution!
