### ISSUE TITLE
Error Message?

### ISSUE THREAD

**Issue by notbushman** [Kalebu/alright#9]
`>>> messenger.find_by_username('username')
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    messenger.find_by_username('username')
TypeError: find_by_username() missing 1 required positional argument: 'username'`

**Comment by Kalebu** [comment]
That is more likely to occur when you try to access the method *find_by_username()* without firstly creating an instance of *WhatsApp*, Can you show more of the full snippet you're trying to run ?

**Comment by Kalebu** [comment]
I'm closing this issue due to long-time of inactivity and zero feedback provided.
